version: '3'
services:
  nginx:
    container_name: nginx_test
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - $PWD/nginx_home/html/:/usr/share/nginx/html
      - $PWD/nginx_home/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx_home/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
networks:
  net: