version: '3'
services:
    nginx-proxy:
        container_name: nginx_proxy
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - net

    web1:
        container_name: web1
        image: nginx
        restart: always
        expose:
            - "80"
        volumes:
            - $PWD/html/:/usr/share/nginx/html:ro
        environment:
            - VIRTUAL_HOST=cervus.localhost,www.cervus.localhost
        networks:
            - net
      
    web2:
        container_name: web2
        image: nginx
        restart: always
        expose:
            - "80"
        volumes:
            - $PWD/html2/:/usr/share/nginx/html:ro
        environment:
            - VIRTUAL_HOST=cervus2.localhost,www.cervus2.localhost
        networks:
            - net
networks:
    net: